version: '3.4'

services:
  keepalive:
    image: ${DOCKER_REGISTRY-}keepalive
    build:
      context: .
      dockerfile: KeepAlive/Dockerfile
    environment:
     KEEP_ALIVE_URL: ""
     KEEP_ALIVE_DELAY: "5"
     URL_IS_SITEMAP: "0"
    volumes:
      - type: bind
        source: /c/keepaliveconfig
        target: /keepaliveconfig
